(() => {
  const dlg = document.getElementById('awsDlg');
  const external = document.getElementById('externalId');
  const picker = document.getElementById('regionPicker');
  if (!dlg || !external || !picker) return;

  // Make it explicit that the External ID is generated by SafetyCheck.
  const externalLabel = external.closest('label');
  if (externalLabel && !externalLabel.querySelector('.external-id-caption')) {
    [...externalLabel.childNodes]
      .filter(n => n.nodeType === Node.TEXT_NODE && n.textContent.trim())
      .forEach(n => n.remove());

    const caption = document.createElement('span');
    caption.className = 'external-id-caption';
    caption.innerHTML = '<span>External ID</span><em>자동 생성된 값</em>';
    externalLabel.insertBefore(caption, external);
  }

  const REGIONS = [
    ['ap-northeast-1','도쿄'],
    ['ap-northeast-2','서울'],
    ['ap-northeast-3','오사카'],
    ['ap-southeast-1','싱가포르'],
    ['ap-southeast-2','시드니'],
    ['ap-southeast-3','자카르타'],
    ['ap-southeast-4','멜버른'],
    ['ap-southeast-5','말레이시아'],
    ['ap-southeast-6','뉴질랜드'],
    ['ap-southeast-7','태국'],
    ['ap-south-1','뭄바이'],
    ['ap-south-2','하이데라바드'],
    ['ap-east-1','홍콩'],
    ['ap-east-2','타이베이'],
    ['us-east-1','버지니아 북부'],
    ['us-east-2','오하이오'],
    ['us-west-1','캘리포니아 북부'],
    ['us-west-2','오리건'],
    ['ca-central-1','캐나다 중부'],
    ['ca-west-1','캘거리'],
    ['mx-central-1','멕시코 중부'],
    ['eu-central-1','프랑크푸르트'],
    ['eu-central-2','취리히'],
    ['eu-west-1','아일랜드'],
    ['eu-west-2','런던'],
    ['eu-west-3','파리'],
    ['eu-north-1','스톡홀름'],
    ['eu-south-1','밀라노'],
    ['eu-south-2','스페인'],
    ['me-south-1','바레인'],
    ['me-central-1','UAE'],
    ['il-central-1','텔아비브'],
    ['af-south-1','케이프타운'],
    ['sa-east-1','상파울루']
  ];

  const oldValue = document.getElementById('regionsInput')?.value || 'ap-northeast-1';
  const initiallySelected = new Set(oldValue.split(',').map(v => v.trim()).filter(Boolean));
  if (!initiallySelected.size) initiallySelected.add('ap-northeast-1');

  picker.innerHTML = `
    <div class="region-compact-head">
      <div>
        <b>분석 리전</b>
        <small>조회할 AWS 리전을 선택하세요.</small>
      </div>
    </div>
    <details class="region-select" id="regionSelect">
      <summary>
        <span id="regionSelectSummary">도쿄 · ap-northeast-1</span>
        <span class="region-chevron">▾</span>
      </summary>
      <div class="region-menu">
        <label class="region-option region-option-all">
          <input id="allRegions" type="checkbox">
          <span><b>활성 리전 전체</b><small>AWS 계정에서 활성화된 리전을 자동 조회</small></span>
        </label>
        <div class="region-divider"></div>
        <input class="region-search" id="regionSearch" type="search" placeholder="리전 이름 또는 코드 검색" autocomplete="off">
        <div class="region-options" id="regionOptions">
          ${REGIONS.map(([code,name]) => `
            <label class="region-option" data-region-row="${code} ${name}">
              <input type="checkbox" data-region-code="${code}" ${initiallySelected.has(code) ? 'checked' : ''}>
              <span><b>${name}</b><small>${code}</small></span>
            </label>`).join('')}
        </div>
      </div>
    </details>
    <input id="regionsInput" type="hidden" value="${[...initiallySelected].join(',')}">
    <div class="region-status" id="regionStatus">선택한 리전만 조회합니다.</div>`;

  const details = document.getElementById('regionSelect');
  const summary = document.getElementById('regionSelectSummary');
  const hidden = document.getElementById('regionsInput');
  const all = document.getElementById('allRegions');
  const search = document.getElementById('regionSearch');
  const options = [...picker.querySelectorAll('[data-region-code]')];
  const menu = picker.querySelector('.region-menu');
  const status = document.getElementById('regionStatus');

  const regionName = code => REGIONS.find(([c]) => c === code)?.[1] || code;

  function selectedCodes() {
    return options.filter(i => i.checked).map(i => i.dataset.regionCode);
  }

  function syncSelection() {
    let selected = selectedCodes();
    if (!selected.length && !all.checked) {
      const tokyo = options.find(i => i.dataset.regionCode === 'ap-northeast-1');
      if (tokyo) tokyo.checked = true;
      selected = selectedCodes();
    }
    hidden.value = selected.join(',');

    if (all.checked) {
      summary.textContent = '활성 리전 전체';
      menu.classList.add('all-mode');
      if (status) status.textContent = '연결 시 AWS 계정의 활성 리전을 자동 확인합니다.';
    } else {
      menu.classList.remove('all-mode');
      if (selected.length === 1) summary.textContent = `${regionName(selected[0])} · ${selected[0]}`;
      else summary.textContent = `${selected.length}개 리전 선택됨`;
      if (status) status.textContent = `선택한 ${selected.length}개 리전만 조회합니다.`;
    }
  }

  options.forEach(input => input.addEventListener('change', syncSelection));
  all.addEventListener('change', syncSelection);

  search.addEventListener('input', () => {
    const q = search.value.trim().toLowerCase();
    picker.querySelectorAll('[data-region-row]').forEach(row => {
      row.hidden = !!q && !row.dataset.regionRow.toLowerCase().includes(q);
    });
  });

  details.addEventListener('toggle', () => {
    if (details.open) setTimeout(() => search.focus(), 0);
  });

  document.addEventListener('click', e => {
    if (details.open && !details.contains(e.target)) details.removeAttribute('open');
  });

  syncSelection();

  const style = document.createElement('style');
  style.textContent = `
    .external-id-caption{display:flex;align-items:center;justify-content:space-between;gap:10px}
    .external-id-caption>span{font-weight:650;color:#dce7f2}
    .external-id-caption>em{font-style:normal;font-size:10px;font-weight:800;color:#70d9a3;background:#12352b;border:1px solid #225a45;border-radius:99px;padding:3px 7px;white-space:nowrap}

    #regionPicker{padding:0!important;border:0!important;background:transparent!important;margin:12px 0 14px!important}
    .region-compact-head{display:flex;justify-content:space-between;align-items:end;margin-bottom:6px}
    .region-compact-head b{display:block;font-size:12px;color:#dce7f2}.region-compact-head small{display:block;margin-top:2px;color:#8195aa;font-size:10px}
    .region-select{position:relative}
    .region-select>summary{list-style:none;display:flex;justify-content:space-between;align-items:center;gap:12px;padding:10px 12px;border:1px solid #29425f;border-radius:10px;background:#081624;color:#edf4fb;cursor:pointer;font-size:12px}
    .region-select>summary::-webkit-details-marker{display:none}.region-select[open]>summary{border-color:#4779a8;border-radius:10px 10px 0 0}
    .region-chevron{color:#89a5bf;transition:transform .15s}.region-select[open] .region-chevron{transform:rotate(180deg)}
    .region-menu{position:absolute;z-index:20;left:0;right:0;top:calc(100% - 1px);padding:10px;border:1px solid #4779a8;border-radius:0 0 12px 12px;background:#091827;box-shadow:0 16px 35px #0008}
    .region-search{width:100%;margin:0 0 8px!important;padding:9px 10px!important;background:#06121e!important;border:1px solid #203b57!important;border-radius:8px!important;color:#fff!important;font-size:11px}
    .region-options{display:grid;grid-template-columns:1fr 1fr;gap:3px;max-height:260px;overflow:auto;padding-right:3px}
    .region-option{display:flex!important;grid-template-columns:none!important;align-items:center!important;gap:9px!important;margin:0!important;padding:8px 9px;border-radius:8px;cursor:pointer;color:#d8e4ef}
    .region-option:hover{background:#10273d}.region-option input{width:15px!important;height:15px!important;min-width:15px;margin:0!important;padding:0!important;accent-color:#58a9ff}
    .region-option span{min-width:0}.region-option b{display:block;font-size:11px;line-height:1.25}.region-option small{display:block;margin-top:2px;color:#7f95aa;font-size:9px;line-height:1.25}
    .region-option-all{padding:9px 8px;margin-bottom:2px!important}.region-option-all b{font-size:12px}.region-divider{height:1px;background:#1c334b;margin:7px 0 9px}
    .region-menu.all-mode .region-options{opacity:.42;pointer-events:none}
    #regionPicker .region-status{margin-top:6px;font-size:9px;color:#71879c;line-height:1.4}
    #regionsInput{display:none!important}
    @media(max-width:650px){.region-options{grid-template-columns:1fr}.region-menu{position:static}.external-id-caption{align-items:flex-start}}
  `;
  document.head.appendChild(style);
})();
